1. How many negative numbers are there?

2. How many positive numbers are there?

3. How many even positive numbers are there?

4. If you were to add 3 to each data point, how many positive numbers would there be?

5. If you squared each number, what would the new mean and standard deviation be?

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z = x − μ /σ

In [1]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [2]:
#1
print(a[a < 0])
len(a[a < 0])

[-2 -1 -6 -7]


4

In [4]:
#2
print(a[a > 0])
len(a[a > 0])

[ 4 10 12 23  3]


5

In [6]:
#3
print(a[(a>0) & (a%2==0)])
len(a[(a>0) & (a%2==0)])

[ 4 10 12]


3

In [7]:
#4
plus_three = a + 3
print(plus_three[plus_three > 0])
len(plus_three[plus_three > 0])

[ 7 13 15 26  1  2  3  3  3  6]


10

In [8]:
#5
squared_a = a ** 2
print(squared_a.mean())
print(squared_a.std())

74.0
144.0243035046516


In [10]:
centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [11]:
#6
avg_a = a.mean()
avg_a
print('Centered Mean')
(a - avg_a).mean()

Centered Mean


0.0

In [13]:
#7. z-score


mean_a = a.mean()
print(mean_a)

std_a = a.std()
print(std_a)

z_score = (a - a.mean()) / a.std()
z_score

3.0
8.06225774829855


array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [14]:
# 8 More Numpy Practices
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = np.array(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
 #Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
    
sum_of_a = sum(a)
sum_of_a

55

In [16]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)
min_of_a

1

In [17]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a

10

In [18]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.sum(a) / len(a)
mean_of_a

5.5

In [19]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.product(a)
product_of_a

3628800

In [20]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = a % 2 != 0
a[odds_in_a]

In [23]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a % 2 == 0
a[evens_in_a]

array([ 2,  4,  6,  8, 10])

In [25]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])


In [26]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b 
    += sum(row)

SyntaxError: invalid syntax (<ipython-input-26-bd6dbd22820a>, line 5)

In [27]:
np.sum(b)

33

In [28]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

np.min(b)

3

In [29]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

np.max(b)

8

In [30]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
np.mean(b)

5.5

In [32]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
np.product(b)

20160

In [33]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [34]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

            
odds_in_b = b % 2 != 0
b[odds_in_b]

array([3, 5, 7])

In [35]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b = b % 2 ==0
b[evens_in_b]

array([4, 6, 8])

In [37]:
# Exercise 9 - print out the shape of the array b.

print(b)

[[3 4 5]
 [6 7 8]]


In [38]:
# Exercise 10 - transpose the array b.
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [39]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
np.reshape(b, (1,6))

array([[3, 4, 5, 6, 7, 8]])

In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
np.reshape(b, (6,1))

In [41]:
## Setup 3
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [47]:
# Exercise 1 - Find the min, max, sum, and product of c.
print(np.min(c))
print(np.max(c))
print(np.sum(c))
print(np.product(c))

1
9
45
362880


In [48]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [49]:
# Exercise 3 - Determine the variance of c.
c.var()


6.666666666666667

In [52]:
# Exercise 4 - Print out the shape of the array c
np.shape(c)

(3, 3)

In [53]:
# Exercise 5 - Transpose c and print out transposed result.
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [69]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
np.sum(c * np.transpose(c))

261

In [71]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
#c_transpose * c_transpose
np.product(np.transpose(c) * np.transpose(c))


131681894400

In [72]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])


In [73]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [74]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [75]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [76]:
# Exercise 4 - Find all the negative numbers in d
np.negative(d)

array([[ -90,  -30,  -45,    0, -120, -180],
       [ -45,   90,   30, -270,  -90,    0],
       [ -60,  -45,   45,  -90,   45, -180]])

In [77]:
# Exercise 5 - Find all the positive numbers in d
np.positive(d)

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [78]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [79]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [80]:
# Exercise 8 - Print out the shape of d.
np.shape(d)

(3, 6)

In [81]:
# Exercise 9 - Transpose and then print out the shape of d.
np.shape(np.transpose(d))

(6, 3)

In [84]:
# Exercise 10 - Reshape d into an array of 9 x 2
np.reshape(d, (9,2))

#easier code:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [86]:
# wrote most of my code as np.function(x) when I can easily write x.function()

# same-same but just quicker code and know both methods of writing

## notes following:

### Dot Product
- Sum of the products of elements at corresponding indeces
`a = [1, 2, 3]`
`b = [0, 1, 2]`

`[1*0, 2*1, 3*2]`
`[0, 2, 6]`
`sum() = 8

## Numpy Key Takeaways

- Vectorized operations with comparision operators `==`, `>`, `>=`, etc...
- Vectorized operations for matematical operators like `*`,`+`,`/` etc...
- We use arrays of booleans (usually produced by comparison operators) to filter our arrays of data